# Generated by Django 2.2.24 on 2023-05-20 15:04

from django.db import migrations


def connect_flats_with_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'flat')
    Owner = apps.get_model('property', 'owner')
    for owner in Owner.objects.all():
        flat = Flat.objects.filter(owner=owner.owner)
        owner.owned_flats.set(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20230520_1802'),
    ]

    operations = [
        migrations.RunPython(connect_flats_with_owners)
    ]
