# Generated by Django 2.2.24 on 2023-05-31 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20230520_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complained_about_flat',
            new_name='about_flat',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='who_complained',
            new_name='from_whom',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='complaint_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owned_flats',
            new_name='flats',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone',
            new_name='pure_phone',
        ),
    ]
